[WIP] Remove msgpack from python-sdk, addresses #1025
tensorlakeai/indexify pull request #1026
Opened 2024-11-13 08:34 UTC by Default2882

## Context

## What

## Testing

## Contribution Checklist

- [ ] If the python-sdk was changed, please run `make fmt` in `python-sdk/`.
- [ ] If the server was changed, please run `make fmt` in `server/`.
- [ ] Make sure all PR Checks are passing.
<!-- You can run the tests manually:
In `python-sdk/`, run the run `pip install -e .`, start the server and executor, `python test_graph_behaviours.py`.

2024-11-15 02:48 UTC, diptanu commented
@Default2882 This looks fine to me. Let's merge this once we have the other pieces for doing JSON end to end.

2024-11-16 06:59 UTC, diptanu requested changes

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +        info!("json output: {}", String::from_utf8(json_bytes).unwrap());
Remove this

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +        .header("Content-Type", "application/cbor")
Why cbor? It would be the encoding which is on the output just set it to `output.encoding`

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +            .body(Body::from(serde_json::to_vec(&json).unwrap()))
If this needs a byte, you don't need to convert this to json earlier, just pass the json_bytes here directly. If it requires strings, then convert the bytes to a string earlier. Don't unwrap() in APIs

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +    info!(
Remove

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +        .header("Content-Type", "application/cbor")
Same comments as above

2024-11-16 06:59 UTC, diptanu commented on server/src/routes/download.rs
> +            .body(Body::from(serde_json::to_vec(&json).unwrap()))
Same comments as above

2024-11-17 16:39 UTC, diptanu requested changes

2024-11-17 16:39 UTC, diptanu commented on python-sdk/indexify/functions_sdk/graph_definition.py
> +        return get_serializer(self.start_node.compute_fn.payload_encoder)
Should be encoder

2024-11-17 16:39 UTC, diptanu commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +    content_type = "application/cbor"
The mimetype for this is not cbor. I am not quite sure what it would be. Lets use application/pythonpickle

2024-11-18 04:34 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +    content_type = "application/cbor"
I kept it as `cbor` because that's what was being used before I made this changes, not sure if changing to `pythonpickle` will work.

2024-11-18 04:39 UTC, Default2882 commented on python-sdk/indexify/executor/downloader.py
> +        deserialized_content = serializer.deserialize(response.content)
Did not understand the comment, the payload which the downloader will get will be in the `content` field.

2024-11-18 05:05 UTC, diptanu commented on python-sdk/indexify/executor/downloader.py
> +        deserialized_content = serializer.deserialize(response.content)
@Default2882 serializer = get_serializer(response.headers["content-type"]) - would something like this work?

encoder = "json" if response.header["content-type"] is JsonSerializer.content_type

2024-11-18 05:05 UTC, diptanu commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +    content_type = "application/cbor"
It would work, I don't think this is being used anywhere

2024-11-18 05:09 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +    content_type = "application/cbor"
As discussed over discord, will be using `application/octet-stream`

2024-11-18 05:34 UTC, merged