refactor system task executor, system tasks only deleted after last i…
tensorlakeai/indexify pull request #1029
Opened 2024-11-13 22:09 UTC by seriousben

…nvocation

## Context

## What

## Testing

## Contribution Checklist

- [ ] If the python-sdk was changed, please run `make fmt` in `python-sdk/`.
- [ ] If the server was changed, please run `make fmt` in `server/`.
- [ ] Make sure all PR Checks are passing.

2024-11-15 01:51 UTC, diptanu commented on server/state_store/src/state_machine.rs
> +        do_system_task_update(
Can you write some comments on what is happening?

2024-11-15 01:51 UTC, diptanu commented on server/state_store/src/state_machine.rs
> +fn do_system_task_update(
Write some comments on what is happening?

2024-11-15 01:51 UTC, diptanu commented on server/state_store/src/state_machine.rs
> +    do_system_task_update(
What is this for?

2024-11-15 02:24 UTC, seriousben commented on server/state_store/src/state_machine.rs
> +    do_system_task_update(
Thanks I addressed this.

2024-11-15 02:24 UTC, seriousben commented on server/state_store/src/state_machine.rs
> +fn do_system_task_update(
Thanks I addressed this.

2024-11-15 02:24 UTC, seriousben commented on server/state_store/src/state_machine.rs
> +        do_system_task_update(
Thanks I addressed this.

2024-11-15 02:25 UTC, seriousben commented on server/data_model/src/lib.rs
> +    pub completing: bool,
Thanks, as discussed this is now `waiting_for_running_invocations`

2024-11-15 08:04 UTC, diptanu requested changes
Looks good, had some questions and comments about updating state.

2024-11-15 08:04 UTC, diptanu commented on server/src/system_tasks.rs
> +        self.state
Might want to coalesce this write with the previous writes as well. So you could introduce a request object which would take the list of invocation ids to replay and the last key and write into rocksdb in one transaction.

2024-11-15 20:43 UTC, seriousben commented on server/src/system_tasks.rs
> +            self.state
Because we need to take some locks to prevent mutation of data (system task + compute graph) during the transaction, doing a batch ends up failing.


This is with:
```
    db: Arc<TransactionDB>,
    ...
    let mut batch_write = WriteBatchWithTransaction::<true>::default();
    ...
    db.write(batch_write)?;
```

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/dba2f6c4-e248-4549-8dc6-64621979ad98">

---

 I will be moving all these mutations into a single Request so that it becomes transactional. But for now I won't create a batch.

2024-11-15 20:50 UTC, seriousben commented on server/src/system_tasks.rs
> +        let (invocations, restart_key) = self.state.reader().list_invocations(
This is done in replay_invocation already and it consist in checking the version on `ComputeGraph`, `NodeOutput`, `GraphInvocationCtx`.

To keep things simpler I am thinking of leaving it there since it allows locking some of the objects that need to be mutated / deleted for the replay.

2024-11-15 21:18 UTC, seriousben commented on server/src/system_tasks.rs
> +        self.state
This is done. Great idea! Much simpler now.

2024-11-18 17:29 UTC, diptanu approved these changes

2024-11-18 19:44 UTC, merged