Improving metrics with blob, kv, and state duration metrics
tensorlakeai/indexify pull request #1064
Opened 2024-11-26 02:47 UTC by seriousben

## Context

We were missing metrics around blob storage, state storage, and kv storage.
We also had buckets that started at 5 seconds.

## What

Adding metrics to have duration data per different read and write operations.
Also adding millisecond buckets to the histograms.

## Testing

Run the graph behavior test and look at `http://localhost:8900/metrics/service`.

<details>
<summary>Details</summary>

```
# HELP blob_operations_duration_seconds blob store latencies in seconds
# TYPE blob_operations_duration_seconds histogram
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.001"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.005"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.01"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.05"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.1"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="0.5"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="1"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="5"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="10"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="25"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="50"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="75"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="100"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="250"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="500"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="750"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="1000"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="2500"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="5000"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="7500"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="10000"} 110
blob_operations_duration_seconds_bucket{op="get",otel_scope_name="blob-storage",le="+Inf"} 110
blob_operations_duration_seconds_sum{op="get",otel_scope_name="blob-storage"} 0.009765587000000008
blob_operations_duration_seconds_count{op="get",otel_scope_name="blob-storage"} 110
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.001"} 94
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.005"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.01"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.05"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.1"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="0.5"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="1"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="5"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="10"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="25"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="50"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="75"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="100"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="250"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="500"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="750"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="1000"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="2500"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="5000"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="7500"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="10000"} 104
blob_operations_duration_seconds_bucket{op="put",otel_scope_name="blob-storage",le="+Inf"} 104
blob_operations_duration_seconds_sum{op="put",otel_scope_name="blob-storage"} 0.053783284
blob_operations_duration_seconds_count{op="put",otel_scope_name="blob-storage"} 104
# HELP executors_online Number of executors online
# TYPE executors_online gauge
executors_online{otel_scope_name="scheduler_stats"} 1
# HELP fn_output_bytes_total number of bytes ingested for fn outputs
# TYPE fn_output_bytes_total counter
fn_output_bytes_total{otel_scope_name="service-api"} 83368
# HELP fn_outputs_total number of fn outputs
# TYPE fn_outputs_total counter
fn_outputs_total{otel_scope_name="service-api"} 65
# HELP invocation_bytes_total number of bytes ingested during invocations
# TYPE invocation_bytes_total counter
invocation_bytes_total{otel_scope_name="service-api"} 36629
# HELP invocations_total number of invocations
# TYPE invocations_total counter
invocations_total{otel_scope_name="service-api"} 17
# HELP kv_storage_read_duration_seconds K/V store read latencies in seconds
# TYPE kv_storage_read_duration_seconds histogram
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.001"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.005"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.01"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.05"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.1"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="0.5"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="1"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="5"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="10"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="25"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="50"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="75"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="100"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="250"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="500"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="750"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="1000"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="2500"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="5000"} 5
kv_storage_read_duration_seconds_bucket{op="get_ctx_state_key",otel_scope_name="kv-storage",le="7500"} 5
kv_storage_read_duration_ [...]

2024-11-26 21:26 UTC, diptanu requested changes
Looks fine, remove the unwraps please

2024-11-26 21:26 UTC, diptanu commented on server/metrics/src/lib.rs
> +        .unwrap(),
No unwraps

2024-11-26 21:26 UTC, diptanu commented on server/metrics/src/lib.rs
> +                        let value = store_metrics.tasks_completed.read().unwrap();
no unwrap

2024-12-01 19:04 UTC, diptanu commented
@seriousben What is left here? Bunch of new metrics here so we should merge this before making a new release

2024-12-01 19:08 UTC, seriousben commented
@diptanu yeah, let's cut a release Monday.

I will have a bunch of PRs ready including this one.
I also fixed a bunch of edge cases.

2024-12-02 02:36 UTC, seriousben commented on server/metrics/src/lib.rs
> +                        let value = store_metrics.tasks_completed.read().unwrap();
All unwraps were removed

2024-12-02 02:37 UTC, seriousben commented on server/metrics/src/lib.rs
> +        .unwrap(),
Since this happens at initialization time, I was thinking of keeping it.

2024-12-02 02:53 UTC, merged