make scheduler process its work without being blocked on errors
tensorlakeai/indexify pull request #1069
Opened 2024-11-26 21:45 UTC by seriousben

## Context

The scheduler  can get stuck in a loop when unprocessed state changes or unallocated tasks cannot be executed correctly for example when the task or graph do not exist anymore.

## What

This PR makes the control loops of the scheduler log errors instead of existing the control loops.
It also adds fields to logs in order to help debug failures.

## Testing

Run the SDK tests.

## Contribution Checklist

- [ ] If the python-sdk was changed, please run `make fmt` in `python-sdk/`.
- [ ] If the server was changed, please run `make fmt` in `server/`.
- [ ] Make sure all PR Checks are passing.

2024-11-26 21:46 UTC, seriousben commented on server/src/scheduler.rs
> +        for state_change in &processed_state_changes {
Only processing stage changes that were actually correctly processed.

2024-11-26 21:47 UTC, seriousben commented on server/src/scheduler.rs
> +            );
Not sure how helpful this is when debugging. At least will provide some fields on error.

2024-11-26 21:49 UTC, seriousben commented on server/task_scheduler/src/lib.rs
> +            );
```
{"timestamp":"2024-11-26T21:48:30.717931Z","level":"INFO","message":"scheduling task TaskId(\"7b5dfb6c-7205-4286-985c-e0169b4890ee\")","target":"task_scheduler","span":{"compute_fn":"make_it_string","compute_graph":"simple_pipeline","namespace":"default","task_id":"7b5dfb6c-7205-4286-985c-e0169b4890ee","name":"scheduling_task"}}
{"timestamp":"2024-11-26T21:48:30.718015Z","level":"INFO","message":"assigning task TaskId(\"7b5dfb6c-7205-4286-985c-e0169b4890ee\") to executor ExecutorId(\"iYYptSyk7mS1Z3loBA7AN\")","target":"task_scheduler","span":{"compute_fn":"make_it_string","compute_graph":"simple_pipeline","namespace":"default","task_id":"7b5dfb6c-7205-4286-985c-e0169b4890ee","name":"scheduling_task"}}
```

2024-11-26 21:50 UTC, seriousben commented on server/src/scheduler.rs
> +            );
```
{"timestamp":"2024-11-26T21:48:30.721452Z","level":"INFO","message":"compute graph simple_pipeline invocation finished: false","target":"task_scheduler::task_creator","span":{"change_type":"TaskFinished(TaskFinishedEvent { namespace: \"default\", compute_graph: \"simple_pipeline\", compute_fn: \"make_it_string\", invocation_id: \"5653129b88645fc5\", task_id: TaskId(\"7b5dfb6c-7205-4286-985c-e0169b4890ee\") })","state_change_id":"105","name":"process_state_change"}}
```

Actually quite helpful!

2024-11-27 04:45 UTC, diptanu commented
@seriousben Can you run some tests on the following scenarios - 
1. Create a graph, with no executor, invoke the graph(it will create tasks, but no allocations), delete the invocation, bring an executor(it will create allocation) -- expecting something to break here 
2. Create a graph, with an executor, invoke the graph with a function that takes 10 seconds to complete, meanwhile delete the graph, and let the task complete -- expecting something to break. 
3. Run the graph with a map reduce with a sequence of 100000000 and 15 executors running on docker locally. The map and reduce will run concurrently on all the machines -- expecting a lot to break here

2024-12-01 20:28 UTC, seriousben commented on server/src/scheduler.rs
> +            state_changes_processed: processed_state_changes.iter().map(|x| x.id).collect(),
We are mapping the processes_state_changes to their id.

2024-12-01 22:37 UTC, diptanu requested changes

2024-12-01 22:37 UTC, diptanu commented on server/data_model/src/lib.rs
> +    pub fn get_compute_parent(&self, node_name: &str) -> Option<&str> {
get_parerent_nodes

2024-12-01 22:37 UTC, diptanu commented on server/data_model/src/lib.rs
> +        self.edges
We could just precompute this in a hash map in the ComputeGraph object. But the logic seems fine.

2024-12-01 22:37 UTC, diptanu commented on server/src/scheduler.rs
> +                    processed_state_changes.push(state_change);
Can you just add the id here so that you don't have to iterate again and map the list to ids ?

2024-12-01 22:37 UTC, diptanu commented on server/state_store/src/state_machine.rs
> +            txn.delete_cf(
I don't think we should check this in. This feels like a bandaid. Let's investigate some more before we do this.

2024-12-01 22:54 UTC, seriousben commented on server/state_store/src/state_machine.rs
> +            txn.delete_cf(
I fixed the root cause as part of this PR. But without this, we risk loosing executors stuck in a bad state.

I think if this happens in the future it should be an alert and we should debug it.

2024-12-02 00:37 UTC, seriousben commented on server/data_model/src/lib.rs
> +    pub fn get_compute_parent(&self, node_name: &str) -> Option<&str> {
Done

2024-12-02 00:44 UTC, seriousben commented on server/src/scheduler.rs
> +                    processed_state_changes.push(state_change);
Done

2024-12-02 00:45 UTC, seriousben commented on server/state_store/src/state_machine.rs
> +            txn.delete_cf(
Since the root cause is fixed and this will prevent outages in case a similar problem happens in the future, I would like to keep this and have an alert to get us to investigate and fix other root causes.

2024-12-02 01:57 UTC, seriousben commented on server/data_model/src/lib.rs
> +        self.edges
For simplicity and because it is only needed for a edge case, I would like to postpone precomputing it. precomputing comes with challeneges like support for existing graphs that I would prefer not tackle in this PR.

2024-12-02 02:08 UTC, seriousben commented on server/src/scheduler.rs
>          }
This is what could cause the same task to be allocated multiple times.

2024-12-02 13:42 UTC, seriousben commented
Merging to get rid of lots of timing issues. I am happy to make quick changes before next release as needed @diptanu.

2024-12-02 13:43 UTC, merged