feat: include an optional list of tags when deploying a compute graph
tensorlakeai/indexify pull request #1083
Opened 2024-12-05 15:30 UTC by miguelhrocha

## Context

This PR comes from a need for a visual aid to understand which compute graph is being currently deployed on Indexify. 

This can be considered a short-term solution, as there is no constraint on creating graphs with the same tags collection. However, this can enable CI/CD to automatically generate tags based on commit SHAs.

## What

Adds an optional list of tags which are displayed on the Indexify UI.

### Bonus

Sorts the invocations of a compute graph by creation date because that was driving me crazy.

## Contribution Checklist

- [ ] If the python-sdk was changed, please run `make fmt` in `python-sdk/`.
- [ ] If the server was changed, please run `make fmt` in `server/`.
- [ ] Make sure all PR Checks are passing.

2024-12-05 15:41 UTC, seriousben commented on server/data_model/src/lib.rs
> +    pub tags: Vec<String>,
Can you check the behavior when there are no tags in storage?

I believe this will need `#[serde(default)]`

2024-12-05 15:44 UTC, seriousben commented on server/data_model/src/lib.rs
>      pub version: GraphVersion, // Version incremented with code update
Can you add a check in `test_compute_graph_update` to validate that tags can be updated (without versioning the graph).

2024-12-05 15:45 UTC, seriousben commented on server/data_model/src/lib.rs
> +    pub tags: Vec<String>,
We want all existing graphs to default to an empty Vec without erroring out.

2024-12-05 15:51 UTC, seriousben approved these changes
Please make sure:

1. An older python-sdk can create and update graphs (it won't know about tags)
2. Graphs existing on an older server can be fetched with a default of no tags

This is to make sure we don't require wiping storage or force everyone to upgrade their SDK version on deploy.

2024-12-05 17:46 UTC, stangirala commented on python-sdk/indexify/functions_sdk/graph.py
> +        self.tags = tags or []
can we rename these to user tags or deployment tags?

2024-12-05 18:14 UTC, seriousben commented on python-sdk/indexify/functions_sdk/graph.py
> +        self.tags = tags or []
Can you describe why it would be preferable?

2024-12-05 18:16 UTC, stangirala commented on python-sdk/indexify/functions_sdk/graph.py
> +        self.tags = tags or []
I would like it to be very obvious what tags here is to avoid any confusion. Making the naming as obvious as possible helps.

2024-12-05 18:38 UTC, seriousben commented on python-sdk/indexify/functions_sdk/graph.py
> +        self.tags = tags or []
Maybe adding comments would help with removing any confusion.

2024-12-06 08:42 UTC, diptanu requested changes

2024-12-06 17:41 UTC, merged