Made all reads parallel instead of sequential
tensorlakeai/indexify pull request #243
Opened 2024-01-21 15:21 UTC by rakshith-ravi

The way we're doing `BlobStorageBuilder` currently restricts things to bring it into the trait itself, so this is a temporary fix for now. Once we have more time I'll restructure the code to include it into the trait itself

2024-01-21 15:43 UTC, diptanu requested changes

2024-01-21 15:43 UTC, diptanu commented on src/data_repository_manager.rs
> +            let content = task.await.unwrap()?;
Let's remove the unwraps here, and use futures::future::join_all to await for completion of all the tasks.

2024-01-21 16:07 UTC, rakshith-ravi commented on src/data_repository_manager.rs
> +            let content = task.await.unwrap()?;
These unwraps are for when the task panics, which it never will. The `?` after that is for the error from task output itself

2024-01-25 18:32 UTC, diptanu requested changes

2024-01-25 18:32 UTC, diptanu commented on src/blob_storage/mod.rs
> +                    .with_bucket_name(bucket)
Add .with_region(..) here since the control plane or executors could be running in regions which is not where the bucket is at.

2024-01-25 18:36 UTC, rakshith-ravi commented
Rebased with main

2024-01-25 20:07 UTC, merged