Add TaskAllocator and integrate with Coordinator
tensorlakeai/indexify pull request #282
Opened 2024-01-31 03:12 UTC by jackbackes

This commit introduces the TaskAllocator, a dedicated module for task allocation in the Coordinator. Key aspects of this integration include:

- **Centralizing Task Allocation**: The TaskAllocator encapsulates task allocation logic, which was previously part of the Coordinator. This separation of concerns allows for a more focused and manageable approach to task distribution.

- **TaskAllocator Design Rationale**: The TaskAllocator was designed to provide a clear and isolated domain for managing task allocation. This isolation makes it easier to modify and extend task allocation strategies without impacting the broader system.

- **Round Robin Allocation**: Introduced round robin allocation, leveraging the 'priority-queue' crate for optimized task distribution.

- **Integration into Coordinator**: The Coordinator now interacts with the TaskAllocator for task distribution needs. This is achieved through the `get_task_allocator` method, which provides access to the task allocation functionalities.

- **Removed `distribute_work` from Coordinator**: The `distribute_work` method is removed from the Coordinator, as its responsibilities are now covered by the TaskAllocator. Modified `Coordinator` to utilize the new round robin strategy, replacing previous static allocation methods. Lots of state management responsibility specific to the task manager was moved from the App/State layer into a dedicated facade layer to prevent leaking of complexity.

- **State Store Modifications**: Introduced `EvacuateExecutor` request to facilitate task reallocation in response to executor changes.

- **Evacuation and Reassignment in `remove_executor`**: The Coordinator's `remove_executor` method now includes logic to handle task reassignment when an executor is removed, ensuring no loss of tasks during executor evacuation.

2024-01-31 06:46 UTC, diptanu requested changes
Looked at the first couple of files in the PR, have some minor comments and some questions.

2024-01-31 06:46 UTC, diptanu commented on src/coordinator.rs
> +            .evacuate_executor_and_reallocate_tasks(&executor_id)
This will run the scheduler in the middle of the health check handler breaking because an executor dropped out. I think this makes the process of finishing the request handler in-deterministic since we don't know how long the scheduler will take to return. I would suggest removing the executor from shared state and create some event which triggers the scheduler asynchronously.

2024-01-31 06:46 UTC, diptanu commented on src/state/mod.rs
> +        let store = self.store.state_machine.read().await;
TODO - We should look into having a copy on write reference here to avoid copies

2024-01-31 06:46 UTC, diptanu commented on src/state/mod.rs
> +            .filter(|task| task_ids.contains(&task.id))
Convert task_ids to hash set if you are going to do contains so that it's an O(1) lookup vs O(n)

2024-01-31 06:46 UTC, diptanu commented on src/state/store/mod.rs
> +    EvacuateExecutor {
What is this for?

2024-01-31 18:44 UTC, diptanu commented on src/task_allocator/mod.rs
> +use self::work_planner::ExecutorIdRef;
Rename to planner

2024-02-01 00:12 UTC, jackbackes commented on src/coordinator.rs
> +            .evacuate_executor_and_reallocate_tasks(&executor_id)
Reallocations are now reactive to state changes.

2024-02-01 00:13 UTC, jackbackes commented on src/state/mod.rs
> +        let store = self.store.state_machine.read().await;
I played with adding Cow in the ChangeType::NewBinding handler. It's a little clunky, but there may be ways to improve it.

2024-02-01 00:15 UTC, jackbackes commented on src/state/mod.rs
> +            .filter(|task| task_ids.contains(&task.id))
fixed

2024-02-01 00:16 UTC, jackbackes commented on src/state/store/mod.rs
> +    EvacuateExecutor {
removed.

2024-02-01 08:51 UTC, diptanu requested changes
Left some comments related to the task allocator.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +pub struct SchedulerStateFacade {
I don't think this would be very useful. We are not building a general purpose database here on top of the shared state for a separation of application level query layer which does filtering and such. If you find doing some filtering in the scheduler, I would suggest just adding a reverse index in the storage layer to avoid that.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +    async fn get_task_ids_for_executor(
This should be in the shared state api.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +    async fn get_unassigned_task_ids(&self) -> Result<Vec<TaskId>, anyhow::Error> {
Same here and all the methods below.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/planner/round_robin.rs
> +        ignore_executors: Vec<ExecutorIdRef<'_>>,
What is this for?

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +    work_distributor: Box<dyn planner::AllocationPlanner + Send + Sync>,
placement_planner or just task_planner.

2024-02-01 08:51 UTC, diptanu commented on src/state/store/mod.rs
> +    NewBinding {
Bindings should have unique id but it's fine to capture the repository id.

2024-02-01 08:51 UTC, diptanu commented on src/state/store/mod.rs
> +                        if let Some(assigned_tasks) = sm.task_assignments.remove(executor_id) {
Don't do this here, just mark that the executor is removed as a state change and remove the executor from all indexes. Change the task assignments in the scheduler

2024-02-01 08:51 UTC, diptanu commented on src/state/mod.rs
> +        let store = self.store.state_machine.read().await;
Yeah Cow is not very ergonomic in Rust. Let's think about Cow in subsequent PRs, there are some ways to go. After this, we have to revisit how state is stored in disk and then get to the Cow work.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +        let all_tasks = self.shared_state.get_all_task_ids().await?;
Couple of things - 1. If we need all the tasks, a method which does that is more efficient than reading task ids first and then getting all the tasks. 2. Second this would be much better if there was a reverse index of content type and HashSet of Tasks vs reading all the tasks and filtering them here.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +    pub async fn rebalance_all_task_allocations(&self) -> Result<(), anyhow::Error> {
This looks not that efficient, since  there is no point in rebalancing tasks when executors with extractors not matching them are added. I would suggest making this method accept an extractor name, and then find all the tasks for that extractor and rebalancing only them.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +    pub async fn schedule_unallocated_tasks(&self) -> Result<(), anyhow::Error> {
Same here as below, take an extractor as an argument and only allocate tasks that can be allocated vs getting all the unassigned tasks.

2024-02-01 08:51 UTC, diptanu commented on src/task_allocator/mod.rs
> +            .plan_allocations(task_ids, vec![executor_id])
There is no need for this vector here, if the executor is just removed from the shared state before the scheduler is invoked.

2024-02-01 21:33 UTC, jackbackes commented on src/task_allocator/mod.rs
> +    pub async fn rebalance_all_task_allocations(&self) -> Result<(), anyhow::Error> {
this was actually older code, now removed.

2024-02-01 21:34 UTC, jackbackes commented on src/task_allocator/mod.rs
> +        let all_tasks = self.shared_state.get_all_task_ids().await?;
makes sense - adding a reverse lookup by content type.

2024-02-01 21:38 UTC, jackbackes commented on src/task_allocator/mod.rs
> +    pub async fn schedule_unallocated_tasks(&self) -> Result<(), anyhow::Error> {
hmm... the purpose of this method is to allocate tasks after content is added or after an executor has been removed (and tasks have been de-allocated). We have a separate method for allocating tasks matching an executor, which is used when a new binding or executor is added.

2024-02-01 21:38 UTC, jackbackes commented on src/task_allocator/mod.rs
> +            .plan_allocations(task_ids, vec![executor_id])
ack

2024-02-03 17:31 UTC, diptanu requested changes

2024-02-03 17:31 UTC, diptanu commented on src/coordinator.rs
> +                if let Some(unassigned_tasks) = sm.task_assignments.remove(executor_id.as_str()) {
These mutations on state machine directly outside of the state store shouldn't be here. Because the writes are happening to the Raft state under the hood, they needs to be requests to Raft for mutations. This will simply not work. The comment is for your information.

2024-02-05 21:20 UTC, diptanu requested changes

2024-02-05 21:20 UTC, diptanu commented on Cargo.toml
> +mockall = { workspace = true }
Can this be included only for tests?

2024-02-05 21:20 UTC, diptanu commented on src/state/mod.rs
> +            .all_tasks()
We already have an index of task_id -> Task in the state machine, use that to get the tasks vs getting all the tasks and then filtering them like this.

2024-02-05 21:20 UTC, diptanu commented on src/state/mod.rs
> +        self.get_unfinished_task_ids_by_content_type(
This is not going to work because there might be unfinished tasks of the same mime type on other executors. Ether - 1. Filter the unfinished tasks by tasks with the executor id, or create a reverse index of unfinished tasks by executor id( executor_id -> HashSet<Task>).

2024-02-05 21:39 UTC, diptanu requested changes

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/mod.rs
> +            .commit_task_assignments(plan.into_task_executor_allocations())
Everywhere you get a plan, you are changing it from ExecutorId -> HashSet<TaskID> to TaskID->Executor, change the planner to return the task to executor mapping instead to prevent this.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/mod.rs
> +    /// Reschedule all tasks that match the executor's input mime types, even if
We can't simply match extractor's mime type, it has to match the extractor name also. There could be several extractors which work off PDF documents for example, but if an invoice extractor dies, we need to reschedule the tasks on that executor to others which are running the same extractor.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/mod.rs
> +    async fn reallocate_all_tasks_matching_content_types(
Matching extractors, content type would be matched automatically.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/mod.rs
> +/// Separated out so it can be mocked, and the entire state doesn't need to be
Do we need this if we setup a single node in-memory shared state? It's super fast anyways, based on the test in coordinator.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/planner/plan.rs
> +    pub fn into_task_executor_allocations(&self) -> HashMap<TaskId, ExecutorId> {
Let's make the planner return TaskId -> ExecutorID if that's what is most commonly used.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/planner/round_robin.rs
> +        let mut plan = TaskAllocationPlan(HashMap::with_capacity(extractor_executors_map.len()));
Hmm, returning TaskId -> ExecutorID would be better for this as well, we won't have to allocate hashes as the number of executors in the cluster.

2024-02-05 21:39 UTC, diptanu commented on src/task_allocator/planner/round_robin.rs
> +        for (extractor, executors) in extractor_executors_map.iter() {
Instead of doing this everytime, just cache it. And adjust it everytime new allocations are being done.

2024-02-06 19:26 UTC, diptanu requested changes

2024-02-06 19:26 UTC, diptanu commented on src/state/mod.rs
> +    pub async fn all_tasks(&self) -> Result<Vec<internal_api::Task>> {
This is no longer needed.

2024-02-06 19:26 UTC, diptanu commented on src/state/mod.rs
> +        future::join_all(task_ids.iter().map(|id| self.task_with_id(id)))
There is no point of doing these in parallel as these are objects in memory, just serially going over them and doing hash lookups is enough. Unless these operations are blocking in some way or compute bound doing parallel copy from memory location A to B doesn't speed things up.

2024-02-06 19:26 UTC, diptanu commented on src/state/mod.rs
> +        self.get_task_ids_for_extractor(&executor.extractor.name.as_str())
Looks like you are getting all the task ids for a given extractor. The name doesn't feel right. Or are you getting all the task ids for a given executor id?

2024-02-06 19:26 UTC, diptanu commented on src/state/mod.rs
> +        drop(sm);
Why are you dropping the sm? Once the method exits, the read lock is going to dropped.

2024-02-06 19:26 UTC, diptanu commented on src/state/mod.rs
> +            .unfinished_tasks_by_extractor
Rename this method to say unfished_tasks_by_executor

2024-02-06 19:26 UTC, diptanu commented on src/state/store/mod.rs
> +pub type ExtractorExecutorsMap = HashMap<String, HashSet<String>>;
HashMap<ExecutorId, HashSet<ExecutorId>>

2024-02-06 19:26 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +                        *self.executor_load.entry(executor_id.clone()).or_default() -= 1;
The type for this is usize, we need a check over here to make sure we are not decrementing beyond zero.

2024-02-06 19:26 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +        for extractor in tasks_by_extractor.keys() {
Are we not using the data from the state machine?

2024-02-06 20:10 UTC, jackbackes commented on src/state/mod.rs
> +        self.get_task_ids_for_extractor(&executor.extractor.name.as_str())
I'm going to drop this method and the corresponding "reallocate_all_tasks_matching_executor" - the idea here was to find all the tasks that are compatible with the executor (i.e. that share the same extractor with the executor) but it's simpler to just have a "reallocate_all_tasks_matching_extractor" method and have the calling function get the extractor name.

2024-02-06 20:11 UTC, jackbackes commented on src/state/mod.rs
> +        drop(sm);
I was running into an issue where tests were hanging because of a deadlock, so I got a little overzealous with explicitly dropping the lock. But yeah, it's not needed here.

2024-02-06 20:13 UTC, jackbackes commented on src/state/mod.rs
> +            .unfinished_tasks_by_extractor
this is a mapping of extractor name to task, so renaming to unfinished_tasks_by_extractor

2024-02-06 20:19 UTC, jackbackes commented on src/state/store/state_machine_objects.rs
> +                        *self.executor_load.entry(executor_id.clone()).or_default() -= 1;
Added.

2024-02-06 20:34 UTC, jackbackes commented on src/task_allocator/planner/load_aware_distributor.rs
> +        for extractor in tasks_by_extractor.keys() {
updated to iterate over executor load, since we can assume it's guaranteed that any executor exists in the index.

2024-02-06 20:35 UTC, jackbackes commented on src/state/mod.rs
> +        future::join_all(task_ids.iter().map(|id| self.task_with_id(id)))
Method isn't necessary anymore. Dropping.

2024-02-06 22:27 UTC, diptanu requested changes

2024-02-06 22:27 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +    load: usize,
`num_running_tasks`

2024-02-06 22:27 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +        let extractor_executors_map = self.shared_state.get_extractor_executors_map().await;
Please remove this since we are not using this

2024-02-07 18:52 UTC, merged