Cluster Membership Changes Via Seed Node
tensorlakeai/indexify pull request #389
Opened 2024-03-01 08:54 UTC by redixhumayun

This PR aims to allow any nodes that start up in the cluster to get the current state of cluster membership by contacting the seed node.

To accomplish this:

* A seed node has been added to the .yaml file. Two additional .yaml files have been added but those are only to make testing easier. 
* A new RPC has been defined in the `proto` file and an implementation provided. This implementation uses the methods `add_learner` and `change_membership` provided by `OpenRaft` to update cluster configuration. It follows [this example](https://github.com/datafuselabs/openraft/blob/d041202a9f30b704116c324a6adc4f2ec28029fa/examples/raft-kv-memstore/tests/cluster/test_cluster.rs#L75-L103).
* A node will start a recurring `tokio` task to contact seed node regularly and check cluster membership. Upon receiving a request from a node not currently in the cluster, the seed node will update the cluster configuration for all the nodes.

This currently works when 1 new node joins a cluster. However, when another node joins the cluster, it fails.

Difficulties I am facing:

* How do I reliably test this? I keep have to run `run_tests.sh` to clear up any state between node restarts but this works only for the leader node. The remaining nodes don't seem to have their states cleaned up between restarts.
* Also, when I run `run_tests.sh`, the test `test_form_raft_cluster` seems to be hanging. Eventually I see `test coordinator::tests::test_form_raft_cluster has been running for over 60 seconds` but shouldn't the test have failed within 10 seconds?

2024-03-02 22:33 UTC, diptanu requested changes
Looking good overall but we need to change a few things.

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +            let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(3));
Move this to a constant

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +    pub fn start_periodic_membership_check(self: &Arc<Self>) {
Pass in a shutdown. Pass shutdown_rx into this, and do select! on either the ticker or the shutdown_rx to unblock sleeping the loop, and if shutdown is unblocked, write logs that the membership check is stopping, stop the ticket and return our the task.

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +        let addr = format!("localhost:{}", self.raft_port);
This feels wrong, use the seed_addr from the server_config for this.

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +                info!("Cluster membership response: {:?}", resp);
Remove the logs

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +                let metrics = self.raft.metrics().borrow().clone();
No need to clone the whole metrics, just get reference and only copy out the node names.

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +            .await
.ok_or(|e| anyhow!(...))

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +    fn is_seed_node(&self) -> bool {
Let's change this logic a little and make things a little flexible - let any node be the seed node for another node. All we need from the seed node is the list of other peers it knows in the cluster. And the seed node, needs to be able to forward the request to the leader.

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +                addr: format!("localhost:{}", server_config.raft_port),
What are we doing here?

2024-03-02 22:33 UTC, diptanu commented on src/state/mod.rs
> +    network: Network,
Do we need the whole network implementation here or do you need the gRPC client? I would suggest not having the network implementation here if you need only the client implementation.

2024-03-02 22:33 UTC, diptanu commented on src/state/grpc_server.rs
> +        info!(
Log only if there is a new node discovered.

2024-03-02 22:33 UTC, diptanu commented on src/state/grpc_server.rs
> +        let metrics = self.raft.metrics().borrow().clone();
No need to clone the metrics object, just the nodes are enough.

2024-03-02 22:33 UTC, diptanu commented on src/state/grpc_server.rs
> +            let response = RaftReply {
Let the response always be the known list of nodes in the cluster.

2024-03-02 22:33 UTC, diptanu commented on src/state/grpc_server.rs
> +        match self
.ok_or(|e| ...)

2024-03-03 05:51 UTC, redixhumayun commented on src/state/mod.rs
> +        let addr = format!("localhost:{}", self.raft_port);
@diptanu I'm not using the seed_node address here. I'm using the from node's address which isn't provided in the config file.

2024-03-03 06:03 UTC, redixhumayun commented on src/state/network.rs
> +        let mut client = match client_result {
Assuming you mean `map_err` here

2024-03-03 06:05 UTC, redixhumayun commented on src/state/mod.rs
> +            .await
assuming you mean `map_err` here since its a `Result` not an `Option`

2024-03-03 06:14 UTC, redixhumayun commented on src/state/grpc_server.rs
> +            let response = RaftReply {
Do we want to do anything with this response for now? Because OpenRaft is already handling cluster membership changes for us

2024-03-03 06:19 UTC, diptanu commented on src/state/grpc_server.rs
> +            let response = RaftReply {
A shell response object would be useful in the future if we want to add some information from the seed node about the state of the cluster/leader at the time the new node is trying to join. The response metadata could be logged for example. So lets return an empty object `ClusterMembershipResponse`

2024-03-03 06:40 UTC, diptanu commented on src/state/network.rs
> +        let mut client = match client_result {
Yeah

2024-03-03 06:43 UTC, diptanu commented on src/state/mod.rs
> +        let addr = format!("localhost:{}", self.raft_port);
Oh I see, you are passing along the address of the current machine, in that case it would be the advertise addr, which is the network routable address of the current node. We try to probe the public address of the node first, or let operators configure it via the config. Use the `listen_if` attribute of `ServerConfig` instead of localhost here.

2024-03-03 14:15 UTC, redixhumayun commented on src/state/mod.rs
> +                addr: format!("localhost:{}", server_config.raft_port),
@diptanu This is creating the list of members that a cluster will be initialized with. The `initialize_raft` function has the following lines to show how its being used

```
if !self.is_seed_node() {
            return Ok(());
        }
        match self.raft.initialize(self.nodes.clone()).await {
//  removed for brevity
```

2024-03-03 14:21 UTC, redixhumayun commented on src/state/mod.rs
> +    network: Network,
@diptanu I added the `get_cluster_membership` function into the `Network` impl because it seemed like every other network call followed the same process

`app calls network -> network calls client to get handle -> network makes request -> network returns response` 

It seems odd to bypass the network implementation when making a network request. 

Happy to change it though. Instead of storing the network here I would just store the `RaftClient` instead. Let me know.

2024-03-03 14:21 UTC, redixhumayun commented on src/state/mod.rs
> +    fn is_seed_node(&self) -> bool {
@diptanu Can I take care of this in the next PR since that's we plan to tackle leader forwarding?

2024-03-03 15:29 UTC, diptanu commented on src/state/mod.rs
> +    network: Network,
It's fine, yeah.

2024-03-03 15:40 UTC, diptanu requested changes

2024-03-03 15:40 UTC, diptanu commented on protos/raft.proto
> +    string data = 1;
No need for data and error here, leave them empty as we are not using them right now.

2024-03-03 15:40 UTC, diptanu commented on src/coordinator_service.rs
> +        info!("Addr is {}", addr);
Remove this

2024-03-03 15:40 UTC, diptanu commented on src/state/grpc_server.rs
> +                .map_err(|e| Status::internal(format!("Error adding learner: {}", e)));
.map_err(..)?;

2024-03-03 15:40 UTC, diptanu commented on src/state/grpc_server.rs
> +                .map_err(|e| Status::internal(format!("Error changing membership: {}", e)));
Same as above

2024-03-03 15:40 UTC, diptanu commented on src/state/grpc_server.rs
> +                .map_err(|e| Status::internal(format!("Error changing membership: {}", e)));
We also have grpc_helper::internal_err to create errors

2024-03-03 15:40 UTC, diptanu commented on src/state/mod.rs
> +                addr: format!("localhost:{}", server_config.raft_port),
Cool. I hope you have seen my comment about advertise addr (using listen_if from server config)

2024-03-03 15:40 UTC, diptanu commented on src/state/mod.rs
> +    fn is_seed_node(&self) -> bool {
Cool

2024-03-03 17:08 UTC, bshashikant commented
The approach looks good . 
A couple of approaches to handle the seed node unavailability due to seed node failure/network partition etc :
1. Retry with certain sleep for a certain timeout optimistically waiting for the dead node to become available (network partitions may resolve on their own if any)
2. Built Service discovery mechanisms using some centralized persistent  state store like Zookeeper/Etcd/objectStore
3. Deploy Seed Node in HA mode

2024-03-04 04:59 UTC, redixhumayun commented on src/state/mod.rs
> +    pub fn start_periodic_membership_check(self: &Arc<Self>) {
@diptanu Took care of this.

2024-03-04 06:23 UTC, diptanu requested changes
Looks good, some more changes and then we can check it in.

2024-03-04 06:23 UTC, diptanu commented on local_server_config_2.yaml
> +listen_if: 0.0.0.0
Remove this file and the 3rd file. Lets add a docker compose file in a subsequent PR which spins up a 3 node control plane cluster for testing.

2024-03-04 06:23 UTC, diptanu commented on src/state/mod.rs
> +        let raft_srvr = RaftApiServer::new(rpc_server);
Inline the two lines.

2024-03-04 06:23 UTC, diptanu commented on src/state/mod.rs
> +        let addr = format!("{}:{}", self.listen_if, self.raft_port);
Just build cache the addr while initializing the app. no need to copy listen_if and port

2024-03-04 17:58 UTC, merged