Forwardable Raft
tensorlakeai/indexify pull request #397
Opened 2024-03-07 13:54 UTC by redixhumayun

This PR:

* adds forwarding for Raft requests
* creates an abstraction around the Raft instance called ForwardableRaft

2024-03-07 21:07 UTC, diptanu requested changes

2024-03-07 21:07 UTC, diptanu commented on src/coordinator_service.rs
> -    //let mut interval =
Remove

2024-03-07 21:07 UTC, diptanu commented on src/state/forwardable_raft.rs
> +use anyhow::{anyhow, Result as AnyhowResult};
Why import this as AnyhowResult?

2024-03-07 21:07 UTC, diptanu commented on src/state/grpc_server.rs
> +        match self.raft.client_write(request).await {
let _ =  self.raft.client_write(request).map_err(|e| GrpcHelper::internal_err(e.to_string()));
GrpcHelper::ok_response("")

2024-03-07 21:07 UTC, diptanu commented on src/state/forwardable_raft.rs
> +        match self.raft.ensure_linearizable().await {
Remove the match and make the lines read linearly.

2024-03-08 04:37 UTC, redixhumayun commented on src/state/forwardable_raft.rs
> +use anyhow::{anyhow, Result as AnyhowResult};
@diptanu Because the `AnyhowResult` is just a placeholder until I figure out exactly what needs to be returned from here and there might be places I choose to use `std::Result` in the same file. 

It makes it more readable exactly which `Result` I am using - whether the `std` or `anyhow` version.

2024-03-08 04:38 UTC, redixhumayun commented
@diptanu Overall approach works?

2024-03-08 05:48 UTC, redixhumayun commented on src/state/forwardable_raft.rs
> +use anyhow::{anyhow, Result as AnyhowResult};
@diptanu nvm, i've just used `anyhow::Result` everywhere in this file now

2024-03-08 16:30 UTC, diptanu requested changes

2024-03-08 16:30 UTC, diptanu commented on src/state/network.rs
> +use super::store::requests::Response as RequestResponse;
Rename the Response to StateMachineUpdateResponse perhaps?

2024-03-08 16:30 UTC, diptanu commented on src/state/network.rs
> +    pub async fn forward(&self, target_addr: &str, request: Request) -> Result<(), anyhow::Error> {
Shouldn't this also return the response? We would like every raft response have the node id which handled it.

2024-03-08 16:30 UTC, diptanu commented on src/state/mod.rs
> +        cluster.read_own_write(true).await?;
What is this testing?

2024-03-11 05:12 UTC, redixhumayun commented on src/state/mod.rs
> +        cluster.read_own_write(true).await?;
Currently it's an implementation which checks that any write made to the cluster can be read. The `read_own_write` method also accepts a boolean which can be used to change whether write goes to leader or follower to check that raft forwarding works.

2024-03-11 09:40 UTC, redixhumayun commented on src/state/network.rs
> +    pub async fn forward(&self, target_addr: &str, request: Request) -> Result<(), anyhow::Error> {
Taken care of

2024-03-11 09:41 UTC, redixhumayun commented on src/state/network.rs
> +use super::store::requests::Response as RequestResponse;
Renamed `Request` and `Response` to `StateMachineUpdateRequest` and `StateMachineUpdateResponse`. This helps separate naming scheme from `tonic::Request` and `tonic::Response` so its slightly easier to read. 

One problem is that `JoinCluster` falls under `StateMachineUpdateRequest` which it strictly isn't. Have added a note next to it indicating the same.

2024-03-11 18:37 UTC, merged