Write & Read State Machine To RocksDB
tensorlakeai/indexify pull request #406
Opened 2024-03-13 14:38 UTC by redixhumayun

This PR adds functionality to write and read state machine from RocksDB via transactions. Currently works for creating and reading an index. Added tests.

2024-03-15 15:59 UTC, diptanu requested changes

2024-03-15 15:59 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +                .get_from_cf(StateMachineColumns::executors, executor_id)
Can this be a method in the state machine which returns the deserailzied executor?

2024-03-15 15:59 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +            .get_all_rows_from_cf(StateMachineColumns::tasks)
Same here

2024-03-16 04:56 UTC, redixhumayun commented on src/state/store/mod.rs
> +    executors,
Do we want these all to be PascalCase?

2024-03-16 05:31 UTC, redixhumayun commented on src/task_allocator/planner/load_aware_distributor.rs
> +                .get_from_cf(StateMachineColumns::executors, executor_id)
I've added a generic deserialization chained method here

2024-03-16 05:31 UTC, redixhumayun commented on src/task_allocator/planner/load_aware_distributor.rs
> +            .get_all_rows_from_cf(StateMachineColumns::tasks)
I've added a generic deserialization chained method here

2024-03-16 06:23 UTC, diptanu requested changes

2024-03-16 06:23 UTC, diptanu commented on src/state/store/mod.rs
> +                    if let Err(e) = sm.apply_state_machine_updates(req.clone(), &self.db) {
No need to clone

2024-03-16 15:36 UTC, merged