Garbage collection tasks
tensorlakeai/indexify pull request #466
Opened 2024-03-28 15:31 UTC by redixhumayun

2024-03-29 15:11 UTC, diptanu requested changes

2024-03-29 15:11 UTC, diptanu commented on src/state/store/requests.rs
> +    RegisterIngestionServer {
Do we need this? Just keep the ingestion servers in memory on the leader, and use request forwarding to register and remove ingestion servers and get allocations from leader.

2024-04-03 01:52 UTC, diptanu requested changes

2024-04-03 01:52 UTC, diptanu commented on src/vectordbs/qdrant.rs
> +    async fn remove_embedding(&self, index: &str, content_id: &str) -> Result<()> {
Add implementation?

2024-04-03 01:52 UTC, diptanu commented on src/vectordbs/lancedb.rs
> +    async fn remove_embedding(&self, index: &str, content_id: &str) -> Result<()> {
Test?

2024-04-03 01:52 UTC, diptanu commented on src/test_utils.rs
> +                Arc::clone(&garbage_collector),
Why are you cloning the reference?

2024-04-03 01:52 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> -        println!(
Keep it, might be useful to see how long this has taken.

2024-04-03 01:52 UTC, diptanu commented on src/task_allocator/planner/load_aware_distributor.rs
> +        let _coordinator =
why are you creating the coordinator?

2024-04-03 01:52 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +        let txn = db.transaction();
Why is there a transaction? Isn't this just a read?

2024-04-03 01:52 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +        let iterator = txn.iterator_cf(
Are we iterating through all the content in rocks to find the children of the root? If we are might be worth recording the tree in which content appear

2024-04-03 01:52 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +        let mut queue = VecDeque::new();
What is happening here?

2024-04-03 01:52 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +                //  TODO: Insert tombstone marker on content here
Whats the todo?

2024-04-03 04:34 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +                //  TODO: Insert tombstone marker on content here
Mistake. Already took care of the todo

2024-04-03 04:34 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +        let mut queue = VecDeque::new();
Walking the tree using a deque

2024-04-03 04:35 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +        let iterator = txn.iterator_cf(
Yeah, plan to bring that in as part of another PR. Will build an in-memory index of `parent_content_id -> Vec<children_content_id>`

2024-04-03 04:45 UTC, redixhumayun commented on src/test_utils.rs
> +                Arc::clone(&garbage_collector),
`Arc::clone` is always called on a reference to an `Arc`. The constructor for `GarbageCollector` returns an `Arc`

2024-04-03 04:49 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +        let txn = db.transaction();
Yes, but I'm doing two separate reads - one to get the root content and the other to create an iterator. I want a consistent read

2024-04-03 09:47 UTC, merged

2024-04-03 18:10 UTC, diptanu commented on src/coordinator.rs
> +                let gc_task = indexify_internal_api::GarbageCollectionTask {
Move this to an new() function which creates the id and returns an object.

2024-04-03 18:10 UTC, diptanu commented on src/coordinator.rs
> +            let mut hasher = DefaultHasher::new();
These are repeated multiple times. Moving them into the new type will eliminate them.

2024-04-03 18:10 UTC, diptanu commented on src/coordinator.rs
> +                indexify_internal_api::ChangeType::IngestionServerAdded => {
Remove this completely, make the coordinator register unseen ingestion servers when they first send a gc acknowledgment stream

2024-04-03 18:10 UTC, diptanu commented on src/coordinator.rs
> +                indexify_internal_api::ChangeType::IngestionServerAdded => {
Also why are we writing this to the state store? Let's keep these ingestion server related metadata in memory on the leader.

2024-04-03 18:10 UTC, diptanu commented on src/coordinator_service.rs
> +    async fn register_ingestion_server(
Lets remove this and use the task acknowledgment to register these.

2024-04-04 01:28 UTC, diptanu commented on src/state/store/requests.rs
> +    RegisterIngestionServer {
Why is this here?

2024-04-04 01:28 UTC, diptanu commented on src/state/store/requests.rs
> +    RemoveIngestionServer {
Why is this here?

2024-04-04 02:16 UTC, diptanu commented on src/garbage_collector/mod.rs
> +    async fn watch_deletion_events(
How are we ensuring that this happens in the leader? Every coordinator will have state machine changes and thus fire an event.