Update Content
tensorlakeai/indexify pull request #475
Opened 2024-04-03 13:01 UTC by redixhumayun

* added streaming hash (should we use sha2 since it has inbuilt support for hash streaming?)

2024-04-16 07:47 UTC, diptanu requested changes

2024-04-16 07:47 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
> +pub struct ContentMetadataId {
Create a new() here, version will always be 1, so accept only id. If we ever have to override this for tests, we can create the struct directly.

2024-04-16 07:47 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
> +impl TryFrom<&String> for ContentMetadataId {
Repeats what you have below, can't you call the one below by cloning the value? Sell::try_from(value.to_string)

2024-04-16 07:47 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
> +                version: 1,
The id to ContentMetadata doesn't have the version? So we always assume that the API server is working with the latest version? Feels like version: 1 is incorrect, as it needs to point to the latest version or a specific version.

2024-04-16 08:36 UTC, redixhumayun commented on crates/indexify_internal_api/src/lib.rs
> +                version: 1,
But we don't want any component outside of the coordinator to be aware of the version right? So, yes, any request that comes in from the ingestion server will automatically operate on the latest version available. 

All coordinator internal requests will operate on specific versions.

2024-04-16 23:51 UTC, diptanu requested changes

2024-04-16 23:51 UTC, diptanu commented on src/state/mod.rs
> +            let latest_version = self
Getting the latest version is the main logic here, everything else is repeated for this function and the one below which does it for a specific version. Can you just call the one below after getting the latest version of every content?

2024-04-16 23:51 UTC, diptanu commented on src/state/mod.rs
> +        if !identical_content.is_empty() {
Why write identical content?

2024-04-16 23:51 UTC, diptanu commented on src/state/mod.rs
> +        if !content_to_be_updated.is_empty() {
All the code here and below is same, why not append the two lists and write in one shot.

2024-04-17 00:05 UTC, diptanu commented on src/coordinator.rs
> +        let is_content_processed = self.shared_state.is_content_processed(&content_id).await;
Couple of questions - 1. Ehat is the statechage? Task Completion with the object id being the task id or the content metadata id? If it's the later why do you need to know if it's processed? And processed by which extraction policy?

2024-04-17 00:06 UTC, diptanu commented on src/coordinator.rs
> +        let previous_version = ContentMetadataId {
Make a new function for this.

2024-04-17 00:06 UTC, diptanu commented on src/coordinator.rs
> +        let content_metadata = content_metadata.first().ok_or_else(|| {
Just add this to the previous statement.

2024-04-17 04:52 UTC, redixhumayun commented on crates/indexify_internal_api/src/lib.rs
> +impl TryFrom<&String> for ContentMetadataId {
@diptanu I did this to avoid having to clone values for `ContentMetadataId`. Or rather, I think it would be better to get rid of the one below and just use a reference everywhere. What do you think?

2024-04-17 04:53 UTC, redixhumayun commented on protos/coordinator_service.proto
> +    string hash = 11;
The content hash that's constructed on the ingestion server from the content frames. Should I call it `content_hash` or something?

2024-04-17 12:08 UTC, redixhumayun commented on protos/coordinator_service.proto
> +    string hash = 11;
This is resolved

2024-04-17 12:48 UTC, redixhumayun commented on crates/indexify_internal_api/src/lib.rs
> +impl TryFrom<&String> for ContentMetadataId {
`TryFrom<String>` now calls `TryFrom<&String>` internally

2024-04-17 14:44 UTC, redixhumayun commented on src/coordinator.rs
> +        let is_content_processed = self.shared_state.is_content_processed(&content_id).await;
`ChangeType::TaskCompleted` now has a field called `content_id` and uses `task.id` as `object_id`

2024-04-17 16:32 UTC, diptanu requested changes

2024-04-17 19:16 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +        let epoch_time = policy_completion_time
@diptanu it looks like you've already taken care of this. The timestamp is being set in `update_task` in `state/mod.rs`

2024-04-17 19:25 UTC, redixhumayun commented on src/coordinator.rs
> +        let content_metadata = content_metadata.first().ok_or_else(|| {
I can't do that since a Vec returned from a function is a temp value

2024-04-17 19:43 UTC, redixhumayun commented on src/state/mod.rs
> +            let latest_version = self
Yeah, `tombstone_content_batch` now calls `tombstone_content_batch_with_version`

2024-04-19 07:58 UTC, merged