Delete content changes
tensorlakeai/indexify pull request #481
Opened 2024-04-04 11:29 UTC by redixhumayun

2024-04-04 23:54 UTC, diptanu requested changes

2024-04-04 23:54 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +pub struct IndexifyState {
Why wrap the data in state? Initialize the IndexifyState with rx, tx, and pass the tx to the state machine. And whenever the coordinator requests for the rx, clone and hand it out. This abstraction doesn't feel necessary just to wrap the internal state machine store and the sender.

2024-04-04 23:54 UTC, diptanu commented on protos/raft.proto
> +    rpc RegisterIngestionServer(RaftRequest) returns (RaftReply);
Can we move them to the Coordinator Service GRPC API?

2024-04-05 03:43 UTC, redixhumayun commented on protos/raft.proto
> +    rpc RegisterIngestionServer(RaftRequest) returns (RaftReply);
But that's where I had it initially. Why move it back again?

2024-04-05 03:45 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +pub struct IndexifyState {
That's what I tried initially. Ran into issues with serialisation and de-serialisation. Serde skip directive didn't work. 

It's easy to change this in the future cause this file is self-contained

2024-04-05 20:11 UTC, merged