implement server and coordianator metrics
tensorlakeai/indexify pull request #507
Opened 2024-04-14 21:48 UTC by maxkozlovsky

Add metrics for number and bytes of uploaded and extracted contents.

Add metrics for tasks completed/failed, current number of tasks and executors in progress.

2024-04-16 01:45 UTC, diptanu requested changes

2024-04-16 01:45 UTC, diptanu commented on Cargo.toml
> +prometheus = "0.12.0"
We use opentelemetry, isn’t it possible to use that?

2024-04-17 20:16 UTC, diptanu requested changes

2024-04-17 20:16 UTC, diptanu commented on src/state/mod.rs
> +fn start_server(app: Arc<App>, server_config: &ServerConfig) -> JoinHandle<Result<()>> {
Please move this to the coordinator_server.rs so that the same shutdown handler shuts this server, along with the grpc server.

Or move this into a separate module, but start and stop it in coordinator_service.rs

2024-04-17 20:16 UTC, diptanu commented on src/state/mod.rs
> +        let metrics = Metrics::new(state_machine.clone());
Isn't there a global metrics holder/registry that you can pass around to different modules in the service?

2024-04-17 20:16 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +                    match task.outcome {
Move this code as a function inside the Metrics module and pass the TaskOutcome as a reference to mutate the counters .

2024-04-17 20:21 UTC, maxkozlovsky commented on src/state/mod.rs
> +fn start_server(app: Arc<App>, server_config: &ServerConfig) -> JoinHandle<Result<()>> {
This is the same file where the grpc server is started. The shutdown is handled below, the app.server_handle is used to shutdown.

2024-04-17 20:55 UTC, maxkozlovsky commented on src/state/mod.rs
> +fn start_server(app: Arc<App>, server_config: &ServerConfig) -> JoinHandle<Result<()>> {
ok moved the functions to coordinator_service.rs

2024-04-17 21:16 UTC, maxkozlovsky commented on src/state/store/state_machine_objects.rs
> +                    match task.outcome {
moved into a function

2024-04-17 21:51 UTC, maxkozlovsky commented on src/state/mod.rs
> +        let metrics = Metrics::new(state_machine.clone());
there is a global one, I don't know if it better or necessary to use it.

2024-04-17 22:31 UTC, diptanu requested changes

2024-04-17 22:31 UTC, diptanu commented on src/coordinator_service.rs
> +    .unwrap();
Unwrap is probably not going to work here. Can we return an error and make the startup fail completely. Please test by specifying something wrong.

2024-04-17 22:51 UTC, maxkozlovsky commented on src/coordinator_service.rs
> +    .unwrap();
added check

2024-04-18 04:43 UTC, merged