added metrics for tasks per executor
tensorlakeai/indexify pull request #556
Opened 2024-05-01 10:49 UTC by redixhumayun

Note: additional files have changed as a result of running `make fmt && cargo clippy --fix --allow-dirty`

2024-05-01 13:15 UTC, maxkozlovsky commented
There is  pub executor_running_task_count: ExecutorRunningTaskCount, field already, I think it is equivalent to the new one.

2024-05-01 14:13 UTC, redixhumayun commented
> There is pub executor_running_task_count: ExecutorRunningTaskCount, field already, I think it is equivalent to the new one.

@maxkozlovsky yeah, you're right. I've changed the code. Thanks for pointing it out

2024-05-01 22:01 UTC, diptanu requested changes

2024-05-01 22:01 UTC, diptanu commented on src/metrics/mod.rs
> +                                (*count).try_into().unwrap(),
Can we change the data type for executor running task count and not do unwrap here please? Everything else looks fine.

2024-05-02 15:42 UTC, redixhumayun commented on src/metrics/mod.rs
> +                                (*count).try_into().unwrap(),
@diptanu this is done

2024-05-02 15:44 UTC, merged