Raft snapshot rework
tensorlakeai/indexify pull request #575
Opened 2024-05-08 08:48 UTC by redixhumayun

2024-05-09 14:03 UTC, redixhumayun commented
@diptanu had to make changes to configs on the following

* set size limit on `gRPC` server and client to 10MB (up from default of 4MB), otherwise we run into size limits with snapshots.
* set `install_snapshot_timeout` of 2 seconds on `OpenRaft` config so that larger snapshots can be sent. 

I think both of these should be configurable via the `local_server_config.yml` file and I'd like to add them there. Let me know your thoughts.

2024-05-19 04:26 UTC, diptanu requested changes

2024-05-19 04:26 UTC, diptanu commented on src/main.rs
> +    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
Do we need all this? Guessing something was not working with the existing tracing code?

2024-05-19 04:26 UTC, diptanu commented on src/state/grpc_config.rs
> +impl GrpcConfig {
What is this for? We want to send up to 16 MB?

2024-05-19 04:26 UTC, diptanu commented on src/state/mod.rs
> +            snapshot_max_chunk_size: 4194304, //  4MB
This is 4 MB but the grpc config is 16.

2024-05-19 04:26 UTC, diptanu commented on src/state/network.rs
> +use anyhow::Ok;
Not necessary

2024-05-19 04:26 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +    pub fn build_snapshot(
We need ExtractionGraphs to be added to the snapshot.

Remove ExtractionPoliciesAppliedOnContent since we don't seem to use it.

2024-05-19 04:37 UTC, diptanu commented on src/state/store/mod.rs
> +        let txn = self.db.transaction();
Where is the txn closed ?

2024-05-19 04:37 UTC, diptanu commented on src/state/store/state_machine_objects.rs
> +        let txn = db.transaction();
What happens to this transaction and others? They need to be committed or closed or something no?

2024-05-19 04:49 UTC, diptanu commented on src/main.rs
> -            .with_filter(LevelFilter::from_level(Level::INFO)),
.with_filter(env_filter)

// Initialize the env_filter before this.

2024-05-19 14:12 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +    pub fn build_snapshot(
Done

2024-05-19 14:13 UTC, redixhumayun commented on src/state/mod.rs
> +            snapshot_max_chunk_size: 4194304, //  4MB
Databend configs

2024-05-19 14:13 UTC, redixhumayun commented on src/main.rs
> +    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
Done

2024-05-19 14:13 UTC, redixhumayun commented on src/state/grpc_config.rs
> +impl GrpcConfig {
Databend configs

2024-05-19 14:14 UTC, redixhumayun commented on src/main.rs
> -            .with_filter(LevelFilter::from_level(Level::INFO)),
Done

2024-05-19 14:14 UTC, redixhumayun commented on src/state/store/state_machine_objects.rs
> +        let txn = db.transaction();
Not relevant. No txn in read path anymore

2024-05-19 14:16 UTC, redixhumayun commented on src/state/network.rs
> +use anyhow::Ok;
done

2024-05-20 19:52 UTC, maxkozlovsky reviewed
There is a problem with the implementation that it creates an in-memory copy of the whole database and serializes it into on-disk file. This does not scale with the database size, and eventually will fail the snapshot when database does not fit in memory. Snapshot  should be using rocksdb checkpoint, which is much cheaper to create and does not require storing all db in memory (rocksdb creates hard links to all the level files in checkpoint directory, next time a level file is overwritten with write merge checkpoint retains the state) . To transfer snapshot transfer all files in the rocksdb checkpoint directory, and replace rocksdb dir with that.

2024-05-23 00:06 UTC, merged