support numbers in labels
tensorlakeai/indexify pull request #632
Opened 2024-05-30 17:34 UTC by diptanu

2024-06-04 05:27 UTC, diptanu reviewed
Left some comments

2024-06-04 05:27 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
>      fn from(value: ExtractionPolicy) -> Self {
Make this try_from

2024-06-04 05:27 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
> +            .map_err(|e| anyhow!("unable to convert to protobuff JSON value: {e:?}"))
Try_from

2024-06-04 05:27 UTC, diptanu commented on src/api.rs
> +        let filters_eq = internal_api::utils::convert_map_prost_to_serde_json(value.filters)
Try from

2024-06-04 05:27 UTC, diptanu commented on src/api.rs
> +        let labels = internal_api::utils::convert_map_prost_to_serde_json(value.labels)
Try from

2024-06-04 05:27 UTC, diptanu commented on src/api_utils.rs
> +        // FIXME: edwin this returns Value::String only.
What’s the fix?

2024-06-05 01:03 UTC, maxkozlovsky requested changes
do lance db ignored tests pass now?

2024-06-05 01:03 UTC, maxkozlovsky commented on src/vectordbs/lancedb.rs
> +            arrays.push(from_serde_json_to_arrow_array(some_values[0], all_values)?);
should be checking the column type. the insertion is going to fail if the type does not match to column.

2024-06-05 01:36 UTC, diptanu commented on crates/indexify_internal_api/src/utils.rs
> +        if let Some(n) = &n.as_f64() {
Yes this.

2024-06-05 01:43 UTC, edwinkys commented on crates/indexify_internal_api/src/utils.rs
> +        if let Some(n) = &n.as_f64() {
Thank you. I was looking for this.

2024-06-05 22:31 UTC, edwinkys commented
@maxkozlovsky yes, all of LanceDB tests are green now

2024-06-05 23:26 UTC, maxkozlovsky commented on src/ingest_extracted_content.rs
> +        let root_content = if let Some(content) = root_content {
This is shorter:
```
        let root_content = root_content.map(|c| c.try_into()).transpose()?;
```

2024-06-05 23:26 UTC, maxkozlovsky commented on src/vectordbs/lancedb.rs
> +            let mut some_values = vec![]; // Used to check the type.
This should be simpler. There is no need for some_values since we already have column type and can validate against that.

2024-06-05 23:26 UTC, maxkozlovsky commented on crates/indexify_internal_api/src/lib.rs
> +    pub filters: HashMap<String, serde_json::Value>,
this is changing on-disk data structure, needs to have conversion code to preserve backward compatibility. This will be best done combined with my snapshot PR which also changes on-disk data.

2024-06-05 23:39 UTC, edwinkys commented on crates/indexify_internal_api/src/lib.rs
> +        let mut extraction_policies = vec![];
Thanks, Max. You're the best 👍

2024-06-05 23:40 UTC, edwinkys commented on crates/indexify_internal_api/src/lib.rs
> +            .unwrap();
Thank you for catching this.

2024-06-05 23:42 UTC, edwinkys commented on src/ingest_extracted_content.rs
> +        let root_content = if let Some(content) = root_content {
Oh my god! This is what I've been looking for. Thank you so much for this.

2024-06-07 00:17 UTC, diptanu commented on crates/indexify_internal_api/src/lib.rs
> +            .unwrap();
Remove unwrap here

2024-06-07 00:17 UTC, diptanu commented on src/data_manager.rs
> +                    .map(|g| g.try_into().unwrap())
remove unwrap

2024-06-07 00:17 UTC, diptanu commented on src/data_manager.rs
> +        let labels_eq = internal_api::utils::convert_map_serde_to_prost_json(labels_eq.clone())?;
You can merge the two lines here and remove the clone

2024-06-07 19:03 UTC, merged