add langchain integration example
tensorlakeai/indexify pull request #775
Opened 2024-07-22 17:23 UTC by rishiraj

1. added langchain example by using official langchain tutorial and showing easy integration with Indexify.
2. Made it very crisp and to the point, benefits of Indexify are removed from the example conclusion.
3. Added output image for the code snippet.
4. Removed the table of content in this example as discussed in call.

2024-07-22 21:45 UTC, diptanu requested changes

2024-07-22 21:45 UTC, diptanu commented on examples/pdf/langchain/README.md
> +This README demonstrates how to integrate Indexify with LangChain for a PDF Question-Answering (QA) system. This approach replaces the official LangChain tutorial (https://python.langchain.com/v0.2/d
The tutorial is based on the official Langchain documentation, available at [Langchain Docs](https://python.langchain.com/v0.2/docs/tutorials/pdf_qa/). We have enhanced the tutorial by incorporating the use of Indexify for continuous ingestion and extraction from PDF files. This improvement ensures that the RAG application remains unchanged, even when new PDF files are added to the knowledge base.

2024-07-23 23:23 UTC, diptanu requested changes

2024-07-23 23:23 UTC, diptanu commented on examples/pdf/langchain/README.md
> +os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"
This will override whatever is in the environment. Check if the api key is set otherwise exit the program with a message saying it needs to be set.

2024-07-24 05:16 UTC, rishiraj commented
@diptanu the requested changes are done along with replacing all instances of content_id with ingested_content_id in get_extracted_content.

2024-07-24 15:09 UTC, merged