Update getting-started-basic.mdx to use llama_cpp instead of openai
tensorlakeai/indexify pull request #787
Opened 2024-07-25 13:31 UTC by rishiraj

2024-07-26 17:17 UTC, diptanu requested changes

2024-07-26 17:17 UTC, diptanu commented on docs/docs/getting-started-basic.mdx
> +    name: "entity-extractor"
You could do Content Tabs on Mintlify and use code blocks inside them. So you can have three blocks - Local Model, OpenAI and Mistral.

2024-07-26 17:17 UTC, diptanu commented on docs/docs/getting-started-basic.mdx
> +llm = Llama.from_pretrained(repo_id='microsoft/Phi-3-mini-4k-instruct-gguf', filename='*q4.gguf', verbose=False)
Why not Q8? Wouldn't that work better?

2024-07-27 02:04 UTC, rishiraj commented on docs/docs/getting-started-basic.mdx
> +llm = Llama.from_pretrained(repo_id='microsoft/Phi-3-mini-4k-instruct-gguf', filename='*q4.gguf', verbose=False)
Q8 would become 4.4 GB file download (double of current 2.2 GB) for a very minute difference in results. Also Microsoft provides just q4 and fp16 (around 8 GB) gguf files.

2024-07-27 02:15 UTC, rishiraj commented on docs/docs/getting-started-basic.mdx
> +    name: "entity-extractor"
done

2024-08-01 04:30 UTC, merged