Add Knowledge Graph RAG Pipeline and QA System Examples
tensorlakeai/indexify pull request #905
Opened 2024-10-02 18:05 UTC by PulkitMishra

This pull request adds two new examples to showcase Indexify's capabilities in building knowledge graph-based applications:

1. Knowledge Graph RAG (Retrieval-Augmented Generation) Pipeline:
   - Demonstrates entity extraction, relationship building, and knowledge graph construction
   - Integrates with Neo4j for graph storage and Sentence Transformers for text embedding
   - Provides a complete workflow from text input to graph storage and embedding generation

2. Knowledge Graph Question Answering (QA) System:
   - Showcases natural language question processing and conversion to Cypher queries
   - Utilizes Neo4j for graph querying and Google's Gemini AI for language tasks
   - Implements a fallback mechanism for robust query handling

Key changes:
- Added new directories under `examples/`: `knowledge_graph_generation/` and `knowledge_graph_qa_system/`
- Each new example includes a README.md with setup instructions and usage guidelines
- Updated the main README.md to include links to the new examples
- Implemented Indexify graphs for both knowledge graph workflows
- Added requirements.txt files for each new example

2024-10-03 09:13 UTC, adithyaakrishna commented on examples/knowledge_graph_qa_system/requirements.txt
> +google-generativeai
```suggestion
google-generativeai

```

2024-10-03 09:14 UTC, adithyaakrishna commented on examples/knowledge_graph_qa_system/workflow.py
> +        logging.error(f"An error occurred during execution: {str(e)}")
```suggestion
        logging.error(f"An error occurred during execution: {str(e)}")

```

2024-10-03 09:14 UTC, adithyaakrishna commented on examples/knowledge_graph_generation/workflow.py
> +    main()
```suggestion
    main()

```

2024-10-03 16:10 UTC, diptanu requested changes

2024-10-05 17:50 UTC, PulkitMishra commented
hey @diptanu combined the two into one, as for avoiding loading twice i think instead of a hacky approach we should fix the sdk to do be able to handle it in a better way like we discussed . 

also @adithyaakrishna eol is there in readme and python file but not in requirements.txt just to be consistent with rest of code

(sorry for the force pushed commits, i committed and pushed from inside examples folders and realised later)

2024-10-05 19:44 UTC, PulkitMishra commented on README.md
> +* [Knowledge Graph RAG Pipeline](examples/knowledge_graph_generation/)
done

2024-10-05 19:46 UTC, merged

2024-10-05 19:46 UTC, diptanu commented
@PulkitMishra Lets add a docker compose here so people can spin it up easily and play with it!

2024-10-05 19:48 UTC, PulkitMishra commented
@diptanu should i do it as part of #918 ?