Improve indexify examples
tensorlakeai/indexify pull request #918
Opened 2024-10-05 19:00 UTC by PulkitMishra

# Improve indexify examples

# YouTube Video Summarizer Improvements

## Key Improvements
- **Code Refactoring**: Separated concerns more clearly, improved function naming, and streamlined the main execution flow.
- **Documentation**: Added a comprehensive README that covers installation, usage, and customization.
- **Error Handling**: Implemented more robust error catching and logging to help with debugging and user feedback.
- **Standardization**: Ensured consistent coding style and structure throughout the project.

2024-10-05 19:13 UTC, PulkitMishra commented
what do we want to do with indexify/examples/website_audio_summary ,  indexify/examples/tweetsgenerator, indexify/examples/multi_model_pdf_parser and indexify/examples/image_detection_indexing ?

2024-10-05 20:58 UTC, diptanu requested changes

2024-10-05 20:58 UTC, diptanu commented on examples/video_summarization/README.md
> +   export INDEXIFY_API_KEY=your_indexify_api_key
We don't have this yet

2024-10-05 20:58 UTC, diptanu commented on examples/video_summarization/README.md
> +   python youtube_summarizer.py
Did you test if this works? I think by default it tries to run this with the server?

2024-10-06 11:21 UTC, PulkitMishra commented
@diptanu except for website audio (didnt have elevenlabs credits) rest are tested

2024-10-06 19:31 UTC, diptanu requested changes

2024-10-06 19:31 UTC, diptanu commented on examples/knowledge_graph/Dockerfile
> +FROM python:3.9-slim
Delete this file as discussed offline.

2024-10-06 19:31 UTC, diptanu commented on examples/knowledge_graph/README.md
> +### Option 2: Using Docker Compose
There is an additional step to build the images -

```
indexify-cli build-image workflow.py NLPFunction
indexify-cli build-image workflow.py generate_embeddings
indexify-cli build-image workflow.py  store_in_neo4j
indexify-cli build-image workflow.py  generate_embeddings
```

2024-10-06 19:31 UTC, diptanu commented on examples/knowledge_graph/docker-compose.yml
> +  app:
This needs the container for the 1. server 2. All the images that are required to run the functions.

2024-10-06 19:31 UTC, diptanu commented on examples/video_summarization/docker-compose.yml
> +      dockerfile: Dockerfile
See the comment above about dockerfile

2024-10-06 19:31 UTC, diptanu commented on examples/website_audio_summary/docker-compose.yml
> +      dockerfile: Dockerfile
Same as above

2024-10-08 16:34 UTC, merged