fix: s3 and helm dep
tensorlakeai/indexify pull request #939
Opened 2024-10-10 08:47 UTC by sadath-12

2024-10-10 09:42 UTC, miguelhrocha requested changes
Thank you for the PR @sadath-12! Would you mind adding a short description on the context of this change, and the steps to reproduce the expected deployment?

2024-10-10 09:42 UTC, miguelhrocha commented on operations/k8s/helm/templates/config.yaml
> +  name: indexify
would you mind renaming this to `indexify-server`? We want to keep the door open to config-maps for executors, which would be more explicit.

2024-10-10 09:42 UTC, miguelhrocha commented on operations/k8s/helm/templates/server.yaml
> +            {{- end }}
I believe these volumes are not interchangeable. The server needs a writable path where to write the state, which is not the same as the blobs persisted by minio, or the like.

I would request to mount this unconditionally and set the path to match the one in the config maps state_store_path

2024-10-10 13:01 UTC, sadath-12 commented
thanks @miguelhrocha . Please take a look on changes

2024-10-10 15:33 UTC, miguelhrocha requested changes

2024-10-10 15:33 UTC, miguelhrocha commented on operations/k8s/helm/templates/server.yaml
> +  {{- with .persistence }}
This line is fixing a type 😄, would you mind renaming the attribute in `local.yaml` and `values.yaml` for `persistence` too? Otherwise this deployment doesn't work

2024-10-10 17:05 UTC, sadath-12 commented on operations/k8s/helm/templates/server.yaml
> +  {{- with .persistence }}
wow ..

2024-10-11 13:29 UTC, miguelhrocha commented
@sadath-12 would you mind changing the `persistance` for `persistence` in the `values.yaml` too?

2024-10-13 04:42 UTC, diptanu commented
@sadath-12 Looks good to me, can you please add some steps in the description which you used to test the changes.

2024-10-14 10:57 UTC, miguelhrocha approved these changes
Thank you for this!

2024-10-14 10:58 UTC, merged