feat: updated curl cmds for downloading indexify
tensorlakeai/indexify pull request #946
Opened 2024-10-11 21:57 UTC by adithyaakrishna

2024-10-11 22:24 UTC, diptanu requested changes

2024-10-11 22:24 UTC, diptanu commented on docs/cli-ui/cli.mdx
> +curl https://tensorlake.ai | sh
Just change it to www, the issue is that curl doesn't automatically follow redirects

2024-10-14 20:08 UTC, adithyaakrishna commented on docs/download/index.mdx
> +  curl https://tensorlake.ai | sh
```suggestion
  curl https://www.tensorlake.ai | sh
```

2024-10-14 20:08 UTC, adithyaakrishna commented on docs/usecases/video_rag.mdx
> +curl https://tensorlake.ai | sh
```suggestion
curl https://www.tensorlake.ai | sh
```

2024-10-14 20:09 UTC, merged