WIP add image builder
tensorlakeai/indexify pull request #974
Opened 2024-10-23 21:49 UTC by stangirala

[ ] Run `make fmt`.
[ ] `pip install -e .`, start server and executor, cd to `python-sdk/tests`, `python test_graph_behaviours.py`.

2024-10-23 22:26 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +async def get_compute_graph_from_server(url):
Use http_client.py it has the methods to get compute graph

2024-10-23 22:28 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +async def get_run_strs_from_image(task: Task, protocol, server_addr):
```
async def get_image_info_for_compute_graph(task: Task) -> ImageInfo:
  pass
```

2024-10-23 22:29 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +        run_first = True
We don't need this if we figure out if the image needs bootstrapping.

2024-10-23 22:33 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +                if run_first:
```
if self._require_image_bootstrap:
    image_info = get_image_info(task)
    executor_image_builder(image_info)
    self._require_image_bootstrap = False
```

2024-10-23 22:39 UTC, stangirala commented on python-sdk/indexify/executor/agent.py
> +                            exit(-1)
Don't append a runnable task if this happens, just write a completed task. Add the exception.

2024-10-24 21:42 UTC, stangirala commented on python-sdk/indexify/executor/agent.py
>                  labels=runtime_probe.labels,
should we add the alias here?

2024-10-25 00:55 UTC, diptanu requested changes
Looks great.

2024-10-25 00:55 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
>                  labels=runtime_probe.labels,
Labels doesn't have the image name so its fine.

2024-10-25 00:55 UTC, diptanu commented on python-sdk/indexify/executor/image_dependency_installer.py
> +    if os.path.exists(file_path):
Remove this check since it will always be False when it's a base image.

2024-10-25 00:55 UTC, diptanu commented on python-sdk/indexify/executor/image_dependency_installer.py
> +    file_path = os.path.expanduser("~/.indexify/image_name")
makedirs

2024-10-25 07:27 UTC, diptanu approved these changes
Left some small comments, looks good otherwise!

2024-10-25 07:27 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +        self._executor_failed = False
Rename this to - self._executor_bootstrap_failed

2024-10-25 07:27 UTC, diptanu commented on python-sdk/indexify/executor/agent.py
> +                        self._require_image_bootstrap = False
This should be set to true even if this fails no? so something like Finally: ....

2024-10-25 07:27 UTC, diptanu commented on python-sdk/tests/image_builder_docker_e2e/test_graph_image_builder_broken.py
> +"""
These tests are great. May be rename the folder and the test files to say - image_bootstraper ... We will likely have to build something which actually builds the container images later :)

2024-10-25 07:31 UTC, stangirala commented on python-sdk/indexify/executor/agent.py
> +                        self._require_image_bootstrap = False
If it fails we just use the `self._executor_failed` flag to fail all the subsequent tasks. So we don't have to set it if the bootstrap fails.

2024-10-25 07:57 UTC, merged