(feat): Add support for Json Serialization #984
tensorlakeai/indexify pull request #991
Opened 2024-10-30 18:34 UTC by Default2882

Adds support for Json Serialization #984
Adds `output` method in `Pipeline` class
Made changes in unittests to run locally.

2024-10-31 04:37 UTC, diptanu requested changes

2024-10-31 04:37 UTC, diptanu commented on python-sdk/indexify/functions_sdk/data_objects.py
> +    payload: Union[bytes | str]
you could leave this as bytes. As the payloads can be decoded from bytes to string in the JSONEncoder - `payload.encode("utf-8")`

2024-10-31 04:37 UTC, diptanu commented on python-sdk/indexify/functions_sdk/data_objects.py
>      payload_encoding: str = "cloudpickle"
Literal["cloudpickle", "json"]

2024-10-31 04:37 UTC, diptanu commented on python-sdk/indexify/functions_sdk/indexify_functions.py
> +            return CloudPickleSerializer.deserialize(payload)
You can get the serializer from the get_serializer method in object_serializer

2024-10-31 04:37 UTC, diptanu commented on python-sdk/indexify/functions_sdk/indexify_functions.py
> +        elif payload_encoder == "msgpack":
Payload encoder can't be msgpack, at the moment it's cloud pickle or JSON. So what happens is - 

1. We convert the payload to bytes by either encoding it into cloud pickle or json (and then convert that to bytes)
2. Convert the entire IndexifyData object to bytes using MSGPack. There is really no need to do this if we upload the payload first into indexify server, get some URL back and then encode the IndexifyData as JSON (since it won't have the raw bytes anymore).  But this could be done in another PR.

2024-10-31 04:37 UTC, diptanu commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +        return jsonpickle.encode(data)
what is jsonpickle for? json.dumps should be just fine no?

2024-11-01 16:13 UTC, vcknorket commented
@diptanu @Default2882 Is this expected to be merged soon?

2024-11-01 16:19 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/object_serializer.py
> +        return jsonpickle.encode(data)
the standard json lib does not support conversion of complex objects. Example - 
```
>>> from dataclasses import dataclass
>>> @dataclass
... class Example:
...     data: str
...
>>> ex = Example("test")
>>> import json
>>> json.dumps(ex)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Example is not JSON serializable
>>> import jsonpickle
>>> jsonpickle.encode(ex)
'{"py/object": "__main__.Example", "data": "test"}'
>>>
```

If we want to use the standard json lib, we'd have to write custom json encoding and decoding as shown [here](https://docs.python.org/3/library/json.html) -

#### Specializing JSON object encoding:
```
import json
def custom_json(obj):
    if isinstance(obj, complex):
        return {'__complex__': True, 'real': obj.real, 'imag': obj.imag}
    raise TypeError(f'Cannot serialize object of {type(obj)}')

json.dumps(1 + 2j, default=custom_json)
```

2024-11-01 16:24 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/data_objects.py
> +    payload: Union[bytes | str]
Yes, but this is needed since we are using `jsonpickle` as pointed out by you below.

2024-11-01 16:25 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/data_objects.py
>      payload_encoding: str = "cloudpickle"
This can be - `msgpack` too right? As seen [here](https://github.com/tensorlakeai/indexify/blob/main/python-sdk/indexify/functions_sdk/object_serializer.py#L13)

2024-11-01 16:28 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/indexify_functions.py
> +            return CloudPickleSerializer.deserialize(payload)
Yes that is what I was going for, but as pointed out in this comment [here](https://github.com/tensorlakeai/indexify/issues/984#issuecomment-2447577537) there's some custom logic related to msgpack parsing. 

Would you suggest moving all the custom logic into `MsgPackSerializer` so that I can directly use `get_serializer `?

2024-11-01 16:31 UTC, Default2882 commented on python-sdk/indexify/functions_sdk/indexify_functions.py
> +        elif payload_encoder == "msgpack":
> Payload encoder can't be msgpack, at the moment it's cloud pickle or JSON. 
 But we already have an implementation of supporting msgpack as seen [here](https://github.com/tensorlakeai/indexify/blob/main/python-sdk/indexify/functions_sdk/object_serializer.py#L13)

I don't think I understand comment 1 and 2. Can you provide some code pointers?

2024-11-02 00:41 UTC, diptanu commented on python-sdk/indexify/functions_sdk/data_objects.py
>      payload_encoding: str = "cloudpickle"
@Default2882 No. We are not going to support msgpack .

2024-11-02 18:22 UTC, diptanu commented
@Default2882 Did you run the graph behavior tests?

2024-11-02 18:23 UTC, diptanu reviewed
@Default2882 Please add back the code to deploy the graphs to the server, since these tests are "integration" tests.

2024-11-02 18:23 UTC, diptanu commented on python-sdk/tests/test_graph_behaviours.py
> -        graph = RemoteGraph.deploy(graph)
Why are these deleted? They test the graph with the server.

2024-11-03 05:59 UTC, Default2882 commented on python-sdk/tests/test_graph_behaviours.py
> -        graph = RemoteGraph.deploy(graph)
Added them back

2024-11-03 06:01 UTC, Default2882 commented
> @Default2882 Did you run the graph behavior tests?

I did, we are supposed to start the server using `cargo build && cargo run` and then start an executor from python-sdk using `poetry run indexify-cli executor` and then submit the tests using `poetry run python tests/test_graph_behaviours.py` right?

2024-11-05 17:04 UTC, merged

2024-11-06 04:12 UTC, Default2882 commented
> @Default2882 Thanks for your contribution!! 🚀

Most Welcome!